"""Add goes, flare and ingestion tables

Revision ID: a541577be3f5
Revises: 
Create Date: 2026-06-14 20:37:54.344509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a541577be3f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flareevent',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('peak_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('flare_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region_number', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_flare_class_start_time', 'flareevent', ['flare_class', 'start_time'], unique=False)
    op.create_index('idx_flare_start_time_desc', 'flareevent', [sa.text('start_time DESC')], unique=False)
    op.create_index(op.f('ix_flareevent_event_id'), 'flareevent', ['event_id'], unique=False)
    op.create_index(op.f('ix_flareevent_start_time'), 'flareevent', ['start_time'], unique=False)
    op.create_table('goesxrs',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('satellite', sa.Integer(), nullable=False),
    sa.Column('short_flux', sa.Float(), nullable=True),
    sa.Column('long_flux', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quality_flag', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_goesxrs_timestamp'), 'goesxrs', ['timestamp'], unique=False)
    op.create_table('ingestionrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestionrun_source'), 'ingestionrun', ['source'], unique=False)
    op.create_index(op.f('ix_ingestionrun_status'), 'ingestionrun', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestionrun_status'), table_name='ingestionrun')
    op.drop_index(op.f('ix_ingestionrun_source'), table_name='ingestionrun')
    op.drop_table('ingestionrun')
    op.drop_index(op.f('ix_goesxrs_timestamp'), table_name='goesxrs')
    op.drop_table('goesxrs')
    op.drop_index(op.f('ix_flareevent_start_time'), table_name='flareevent')
    op.drop_index(op.f('ix_flareevent_event_id'), table_name='flareevent')
    op.drop_index('idx_flare_start_time_desc', table_name='flareevent')
    op.drop_index('idx_flare_class_start_time', table_name='flareevent')
    op.drop_table('flareevent')
    # ### end Alembic commands ###
