line = "1530 +     1428   1442      1452  G15  5   XRA  1-8A      C1.8    1.8E-03   2388"
padded = line.ljust(85)

# Adjusted Slicing:
event_id_raw = padded[0:11].strip()
begin_raw = padded[11:18].strip()
max_raw = padded[18:28].strip()
end_raw = padded[28:34].strip()
obs = padded[34:39].strip()
q = padded[39:43].strip()
event_type = padded[43:48].strip()
loc_frq = padded[48:58].strip()
particulars = padded[58:76].strip()
reg_raw = padded[76:].strip()

print("Adjusted slicing results:")
print(f"event_id_raw: '{event_id_raw}'")
print(f"begin_raw: '{begin_raw}'")
print(f"max_raw: '{max_raw}'")
print(f"end_raw: '{end_raw}'")
print(f"obs: '{obs}'")
print(f"q: '{q}'")
print(f"event_type: '{event_type}'")
print(f"loc_frq: '{loc_frq}'")
print(f"particulars: '{particulars}'")
print(f"reg_raw: '{reg_raw}'")
